#server:
#  port: 8761

spring:
  application:
    name: eurekaService
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
  security:
    user:
      name: pspoek
      password: pspo1233